project_id = "efvynopreyliagayqabt"

[functions.reset-user-setup]
verify_jwt = true

[functions.auto-renew-subscriptions]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true
